NumPy Arrays

In [15]:
import numpy as np

In [16]:
mylist = [1, 2, 3]

In [17]:
type(mylist)

list

In [18]:
np.array(mylist)

array([1, 2, 3])

In [19]:
mylist

[1, 2, 3]

In [20]:
myarr = np.array(mylist)

In [21]:
myarr

array([1, 2, 3])

In [22]:
type(myarr)

numpy.ndarray

In [23]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [24]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [25]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [27]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [28]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [34]:
np.linspace(0, 5, 21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [35]:
len(np.linspace(0, 5, 21))

21

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.random.rand(1)

array([0.68948032])

In [41]:
np.random.randn(10)

array([-0.69838721, -0.99967853, -0.74818226, -1.15546401, -0.02036682,
       -0.08339002, -1.29647646, -0.10860614,  0.78434313, -1.11728322])

In [42]:
np.random.randn(2, 3)

array([[ 0.91650008,  1.01541284,  1.5476103 ],
       [ 1.5855439 , -2.01367992, -0.28707869]])

In [44]:
np.random.randint(0, 101, 5)

array([29, 77, 80, 24, 68])

In [46]:
np.random.randint(0, 101, (4, 5))

array([[53, 68, 63, 26, 68],
       [24, 96, 82, 16, 31],
       [56,  3, 53, 38, 59],
       [40, 58,  2, 59, 42]])

In [49]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [50]:
arr = np.arange(0, 25)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [52]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
ranarr = np.random.randint(0, 101, 10)

In [54]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [55]:
ranarr.max()

99

In [56]:
ranarr.min()

2

In [57]:
ranarr.argmax()

5

In [58]:
ranarr.argmin()

7

In [59]:
ranarr.dtype

dtype('int32')

In [61]:
arr.shape

(25,)

In [62]:
arr = arr.reshape(5, 5)

In [63]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [64]:
arr.shape

(5, 5)

In [65]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])